import { defineTest } from "../define-test";

export default defineTest({
  level: "a2",
  skill: "grammar",
  title: "Comparativos y superlativos en ingles",
  summary:
    "Practica formas comparativas y superlativas frecuentes para describir diferencias y extremos.",
  intro:
    "Esta prueba revisa adjetivos cortos, cambios ortograficos y estructuras con 'more', 'most', 'better' y 'worst'.",
  instructions:
    "Completa cada frase con la forma comparativa o superlativa correcta del adjetivo entre parentesis.",
  durationMinutes: 10,
  questions: [
    {
      id: "a2-grammar-comparatives-superlatives-1",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "My brother is ___ than me. (tall)",
      answers: ["taller"],
      explanation:
        "Los adjetivos cortos suelen formar el comparativo con '-er'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-2",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "This exam is ___ than the last one. (easy)",
      answers: ["easier"],
      explanation:
        "En adjetivos terminados en consonante + 'y', cambia 'y' por 'i' y añade '-er'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-3",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "London is ___ than my town. (big)",
      answers: ["bigger"],
      explanation:
        "En 'big' se duplica la consonante final antes de añadir '-er'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-4",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "Your car is ___ than mine. (fast)",
      answers: ["faster"],
      explanation: "La forma comparativa de 'fast' es 'faster'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-5",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "This book is ___ than that one. (interesting)",
      answers: ["more interesting"],
      explanation: "Con adjetivos largos se usa 'more' antes del adjetivo.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-6",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "Today is ___ than yesterday. (cold)",
      answers: ["colder"],
      explanation: "La forma comparativa de 'cold' es 'colder'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-7",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "She is ___ than her sister. (young)",
      answers: ["younger"],
      explanation: "La forma comparativa de 'young' es 'younger'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-8",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "This sofa is ___ than the chair. (comfortable)",
      answers: ["more comfortable"],
      explanation: "Con adjetivos largos se usa 'more' para comparar.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-9",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "Maths is ___ than English for me. (difficult)",
      answers: ["more difficult"],
      explanation: "'Difficult' usa 'more' en comparativo.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-10",
      type: "cloze",
      prompt: "Completa con el comparativo.",
      sentence: "My dog is ___ than your cat. (friendly)",
      answers: ["friendlier", "more friendly"],
      explanation:
        "'Friendly' suele formar el comparativo como 'friendlier', aunque 'more friendly' tambien se acepta.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-11",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "Mount Everest is ___ mountain in the world. (high)",
      answers: ["the highest"],
      explanation: "El superlativo de 'high' es 'the highest'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-12",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "This is ___ film I have ever seen. (bad)",
      answers: ["the worst"],
      explanation: "'Bad' tiene superlativo irregular: 'the worst'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-13",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "She is ___ student in the class. (good)",
      answers: ["the best"],
      explanation: "'Good' tiene superlativo irregular: 'the best'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-14",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "Monday is ___ day of the week for me. (busy)",
      answers: ["the busiest"],
      explanation: "En 'busy', cambia 'y' por 'i' y añade '-est'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-15",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "This restaurant is ___ in the city. (expensive)",
      answers: ["the most expensive"],
      explanation:
        "Con adjetivos largos se usa 'the most' para el superlativo.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-16",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "He is ___ player on the team. (fast)",
      answers: ["the fastest"],
      explanation: "El superlativo de 'fast' es 'the fastest'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-17",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "That was ___ question in the test. (easy)",
      answers: ["the easiest"],
      explanation: "En 'easy', cambia 'y' por 'i' y añade '-est'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-18",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "This is ___ place I know. (beautiful)",
      answers: ["the most beautiful"],
      explanation: "'Beautiful' usa 'the most' en superlativo.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-19",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "My room is ___ room in the house. (small)",
      answers: ["the smallest"],
      explanation: "El superlativo de 'small' es 'the smallest'.",
      points: 5,
    },
    {
      id: "a2-grammar-comparatives-superlatives-20",
      type: "cloze",
      prompt: "Completa con el superlativo.",
      sentence: "It was ___ day of my life. (happy)",
      answers: ["the happiest"],
      explanation: "En 'happy', cambia 'y' por 'i' y añade '-est'.",
      points: 5,
    },
  ],
});
